### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by EmVee381** [tenfyzhong/joplin.vim#2]
hi i am getting this error, can you help?
                                                                                                                          
Error detected while processing /home/nasredin/.vim/plugged/joplin.vim/autoload/joplin.vim:
line   10:
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/nasredin/.vim/plugged/joplin.vim/python3/pyjoplin/win.py", line 68, in init
    self._root = tree.construct_root(self._joplin, options.folder_order_by,
  File "/home/nasredin/.vim/plugged/joplin.vim/python3/pyjoplin/tree.py", line 149, in construct_root
    folders = joplin.get_all(FolderNode)
  File "/home/nasredin/.vim/plugged/joplin.vim/python3/pyjoplin/joplin.py", line 100, in get_all
    return self._get_by_path(cls,
  File "/home/nasredin/.vim/plugged/joplin.vim/python3/pyjoplin/joplin.py", line 86, in _get_by_path
    cur, has_more = self._get_by_path_page(cls, path, page, **kwargs)
  File "/home/nasredin/.vim/plugged/joplin.vim/python3/pyjoplin/joplin.py", line 76, in _get_by_path_page
    items = json['items']
TypeError: list indices must be integers or slices, not str

**Comment by tenfyzhong** [comment]
I want some more infomation. Please show me the result of `http://localhost:41184/folders?token={YOUR_TOKEN}`

**Comment by ursmaheshj** [comment]
hey, it seems TypeError you are trying to fetch values json['items'] but you should not use inverted commas here otherwise it will become string and python doesn't  allow string indices.

**Comment by tenfyzhong** [comment]
> hey, it seems TypeError you are trying to fetch values json['items'] but you should not use inverted commas here otherwise it will become string and python doesn't allow string indices.

It should be a dict, not string

**Comment by EmVee381** [comment]
> I want some more infomation. Please show me the result of `http://localhost:41184/folders?token={YOUR_TOKEN}`

hi sorry for late reply... i just installed plugin with vim-plug by your guide, i am on manjaro everything default and api key is correct... what info do you need?

VIM version 8.2.2814
Python 3.9.4 (default, Apr 20 2021, 15:51:38) 
[GCC 10.2.0] on linux

btw command you want just print json with my folders... i have many i am not sure if i want share my notes folders here


thx

**Comment by EmVee381** [comment]
i solved it, with upgrade... and probably wrong port was exported... everything is ok, thx for assistance
